export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST';
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USERS_ERROR = "FETCH_USERS_ERROR";

export const POST_USERS_REQUEST = 'POST_USERS_REQUEST';
export const POST_USERS_SUCCESS = "POST_USERS_SUCCESS";
export const POST_USERS_ERROR = "POST_USERS_ERROR";